In [1]:
import numpy as np

In [2]:
arr = np.array([ 
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
    [[23, 24, 25], [26, 27, 28]]])
print('3d:\n', arr, ' shape: ', arr.shape)

3d:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[23 24 25]
  [26 27 28]]]  shape:  (4, 2, 3)


### Ellipsis
Expands to the number of : objects needed for the selection tuple to index all dimensions

In [3]:
#This...
arr[...,0]

array([[ 1,  4],
       [ 7, 10],
       [13, 16],
       [23, 26]])

In [4]:
# Is equivalent to this:
arr[:, :, 0]

array([[ 1,  4],
       [ 7, 10],
       [13, 16],
       [23, 26]])