In [2]:
import numpy as np

## Single element indexing

In [5]:
arr1d = np.arange(10)

In [6]:
arr1d[5]

np.int64(5)

In [8]:
arr2d = np.array([[3, 4, 5],[6, 7,8]])

In [9]:
arr2d[1,1]

np.int64(7)

## Slicing

In [3]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])



In [4]:
arr[0, 1]     # 2


np.int64(2)

In [5]:
arr[:, 1]     # [2 5] (second column)


array([2, 5])

In [6]:
arr[1, :]     # [4 5 6] (second row)



array([4, 5, 6])

In [7]:
# Boolean indexing
mask = ((arr % 2) == 0)
print('mask: \n', mask)
arr[mask]     # [4 5 6]
print('arr[mask]:\n', arr[mask])

mask: 
 [[False  True False]
 [ True False  True]]
arr[mask]:
 [2 4 6]
