In [ ]:
import numpy as np

# From Python list
arr = np.array([1, 2, 3])
print('simple 1,2,3:    ', arr)

# Built-in methods
# Make 5 zeros
zeros = np.zeros(5)         # [0. 0. 0. 0. 0.]
print('zeros:           ', zeros)

# Make 2x3 one matrix
ones = np.ones((2, 3))      # 2x3 matrix of ones
print('ones: \n' , ones)

#
arange = np.arange(0, 10, 2)  # [0 2 4 6 8]
print('arange:         ', arange)
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced numbers
print('linspace:         ', linspace)

# Random arrays
random = np.random.rand(3, 3)  # 3x3 random matrix
print('random: \n', random)

simple 1,2,3:     [1 2 3]
zeros:            [0. 0. 0. 0. 0.]
ones: 
 [[1. 1. 1.]
 [1. 1. 1.]]
arange:          [0 2 4 6 8]
linspace:          [0.   0.25 0.5  0.75 1.  ]
random: 
 [[0.57261418 0.79479109 0.5500778 ]
 [0.89245915 0.28604673 0.458257  ]
 [0.78958864 0.68018237 0.48445201]]
